version: '3'

services:
  chrome:
    image: selenium/standalone-chrome
    shm_size: 2g
    hostname: chrome
    privileged: true
    ports:
    - "4444:4444"

  redis:
    image: 'redis:6.2-alpine'
    restart: always
    hostname: redis
    privileged: true
    ports:
      - "6379:6379"

  app:
    build: ./
    container_name: cmstorehh
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - chrome
      - redis
