version: '3'

services:
  selenium:
    image:
      "selenium/standalone-chrome"
    ports:
      - "4444:4444"

  app:
    build: ./
    container_name: cmstorehh
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - selenium
